### ISSUE TITLE
Daily Report from refugee areas

### ISSUE THREAD

**Issue by Gulfa** [who-emro/meerkat_frontend#35]
We have a Refugee Daily Register form to show the type of information required for the northern border area
Basically it is just entering aggregated information for mortality, morbidity and then some additional figures on staffing, consultations etc. Around 10 tablets would be entering this single form and we would need to aggregate the forms data to produce a report. we have three types of report to make - the public health profile, communicable disease and a tabular report of information.

See example reports: 
[Zaatri Surveillance Report Week 04 2016.pdf](https://github.com/who-emro/meerkat_frontend/files/138037/Zaatri.Surveillance.Report.Week.04.2016.pdf)
[Zaatri Detailed Report Week 04 2016.pdf](https://github.com/who-emro/meerkat_frontend/files/138038/Zaatri.Detailed.Report.Week.04.2016.pdf)
[Zaatri Profile Report Week 04 2016.pdf](https://github.com/who-emro/meerkat_frontend/files/138039/Zaatri.Profile.Report.Week.04.2016.pdf)

**Comment by johnhaskew** [comment]
The first version of form entry for refugee register can be found via this link:
https://jor1.emro.info/::YYYH

The plan would be for each clinic to simply complete this single form at the end of each day, rather than to be using case-based entry. The content of the form may change but hopefully this helps to understand the aggregated structure for the form. 

We would need separate reports (as above) to aggregate the various forms from each clinic (we anticipate maximum of 10 tablets to be reporting each day).

I would appreciate your feedback but may be best to set up a separate instance of the site just for this emergency setting, as we have done for RMS?

**Comment by johnhaskew** [comment]
I have included all variables ref_1 to ref_331 in the codes file, which basically covers mortality and morbidity due to CD, NCD, MH and Injuries.

ref_1 to ref_11 shows population, no of consultations, referrals indicators etc.

Some more conditions may be added etc but this is the core for the report. I will share the report template for content and calculated fields in a following comment.

**Comment by johnhaskew** [comment]
Jordan | North Eastern Border Public Health Profile

Key Findings

Information reported in this public health profile represents cumulative cases reported from X outpatient clinics in the North Eastern Border up until end of Epidemiological Week X (X February 2016).

A total of X consultations and X cases reported from X health facilities.
X% female and X% under five years of age.
X% CMR, X% U5MR.
X% morbidity due to communicable disease, including other CD breakdown.
X% morbidity due to non-communicable disease, including NCD breakdown.
X% morbidity due to mental health conditions, including MH breakdown

Public Health Indicators

1. Health Utilisation Rate [(Total no of new consultations / Total population) * 12] 
2. Number of consultations per clinician per day  [Total no of new consultations / Total no of clinicians / Days in reporting period]
3. Hospitalisation rate [Total no of referrals to hospital / Total no of new consultations]
4. Referral rate [Total no of referrals / Total no of new consultations]
5. Crude Mortality Rate (CMR) (/1000/month) [(Total number of mortality / Total population) * 1000]
6. Under-five Mortality Rate (U5MR) (/1000/month) [(Total number of U5 mortality / Total U5 population) * 1000]

Reporting Sites

As before

Demographics

As before


Presenting Complaint

As before, for CD, NCD, MH, Injuries

Gender

As before

Nationality 

As before

Communicable Disease

As before

Non-Communicable Disease

As before

Mental Health

As before

Injuries

As before


More Information

Contact Information
